- README.md
The List Stores example in the README was incorrectly referencing `get_store` instead of `list_stores`.
- Generated by: https://github.com/openfga/sdk-generator/pull/120
- Contributed by: @sebport0
> fix(docs): correct list_stores example in README

- README.md
Edited README.md to create separate code blocks for Read Relationship Tuples example.
[OpenFGA RFC](https://github.com/openfga/rfcs)
[Contributing to OpenFGA](https://github.com/openfga/.github/blob/main/CONTRIBUTING.md)
> chore(docs): split Read examples in README to separate sections

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/workflows/main.yaml
- .openapi-generator/FILES
- README.md
- openfga_sdk/api_client.py
1. Fix typo in README's read example 
2. Bring in changes for header generator
Related to https://github.com/openfga/sdk-generator/pull/141
> fix: correct typo in README read example

- openfga_sdk/client/client.py
- openfga_sdk/sync/client/client.py
*    feat(client): run sync batch_check with ThreadPoolExecutor for parallelism
*    feat(client): use asyncio semaphore for streaming batch check
Generated by https://github.com/openfga/sdk-generator/pull/228
> feat: batch check updates

- README.md
Fixing incorrect path for synchronous client in README.md
> fix(docs): incorrect path for sync client README

- openfga_sdk/client/configuration.py
As reported in #49, the user needs to be able to pass the path to their own certificate in order to support requests using an old version of the module `requests==2.2.0`.
In order to be able to successfully communicate with fga, the user needs to pass their own custom ssl_ca_cert since they are on an older version of `requests` and `urllib3`. The error they are getting is the following:
```
MaxRetryError: HTTPSConnectionPool(host='api.us1.fga.dev', port=443): Max retries exceeded with url: /stores/01HHFHCC0PBS22DEGPJGFDE2W3/write (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
```
This pull request extends the `ClientConfiguration` class to also receive the `ssl_cert_ca` param to pass down to the …
> feat: allow passing in custom ssl certs to client config

- README.md
Changes are based on `openfga-sdk==0.4.0`
1. Wherever we are using some modules from the `openfga_sdk` I have imported them and keep them as comments.
2. I found some syntax errors in existing code, so i fixed them
3. I have reformatted the code
4. I have added return statement on main function from there we are doing some query 
https://github.com/openfga/python-sdk/issues/28
> chore(docs): clean up and fix imports and initialization in README

- README.md
- example/example1/example1.py
- openfga_sdk/api_client.py
- openfga_sdk/client/configuration.py
- openfga_sdk/configuration.py
- openfga_sdk/sync/api_client.py
- test/test_client.py
- test/test_client_sync.py
- test/test_open_fga_api.py
- test/test_open_fga_api_sync.py
Adds support for an `api_url` configuration option and deprecated the existing `apiHost` and `apiScheme` options
Part of openfga/sdk-generator/issues/298
Generated from: https://github.com/openfga/sdk-generator/pull/302
> feat: support api_url configuration option

- openfga_sdk/oauth2.py
- openfga_sdk/sync/oauth2.py
- test/test_oauth2.py
- test/test_oauth2_sync.py
Moves the client to use `application/x-www-form-urlencoded` for the content type when making token requests per the spec.
In order to do this we set the header on the request and provide `post_params` instead of `body` on the request.
Part of https://github.com/openfga/sdk-generator/issues/284
Generated from https://github.com/openfga/sdk-generator/issues/308
> fix: use correct content type for token request

- openfga_sdk/api_client.py
- openfga_sdk/sync/api_client.py
- test/test_open_fga_api.py
- test/test_open_fga_api_sync.py
This PR extends the SDK's auto-retry function of certain failed HTTP requests, based on the response's HTTP status code, to include 5xx series errors (not including 501s.)
Closes #73
> feat: support auto-retries of 5xx HTTP responses

- .gitignore
- openfga_sdk/client/client.py
- openfga_sdk/sync/client/client.py
- test/test_client.py
- test/test_client_sync.py
This pull request removes the `ReadAuthorizationModel` calls in `BatchCheck` and writes.
- https://github.com/openfga/sdk-generator/issues/314
> fix: remove `ReadAuthorizationModel` calls from `BatchCheck` and writes

- openfga_sdk/client/models/tuple.py
Changes type of condition property on ClientTuple
ClientTuple's property condition is by default set to None - indicating it is nullable. 
It's type does not reflect that however. Therefore I have simply added a union between the existing typ RelationshipCondition and None.
- [ X] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [X ] The correct base branch is being used, if not `main`
- [X ] I have added tests to validate that the change in functionality is working as expected
> Fix: ClientTuple condition property type

- README.md
- example/example1/example1.py
- openfga_sdk/client/models/list_users_request.py
- test/test_client.py
- test/test_client_sync.py
This pull request fixes the `ClientListUsersRequest` class, which incorrectly accepts a `str` type for `object` rather than an `FgaObject` assignment. For consistency's sake, it also improves the type hinting of the other class properties.
- Resolves #97
> fix: `list_users` should accept `FgaObject` type

- .github/workflows/main.yaml
This PR updates the GitHub workflow, bumping the `setup-python` action from `5.1.0` to `5.1.1`.
https://github.com/openfga/sdk-generator/pull/394
> chore(ci): bump `setup-python` action

- openfga_sdk/__init__.py
- openfga_sdk/api/open_fga_api.py
- openfga_sdk/api_client.py
- openfga_sdk/configuration.py
- openfga_sdk/oauth2.py
- openfga_sdk/sync/api_client.py
- openfga_sdk/sync/oauth2.py
- openfga_sdk/sync/open_fga_api.py
- openfga_sdk/telemetry/__init__.py
- openfga_sdk/telemetry/attributes.py
- openfga_sdk/telemetry/configuration.py
- openfga_sdk/telemetry/histograms.py
- openfga_sdk/telemetry/metrics.py
- openfga_sdk/telemetry/telemetry.py
- test/telemetry/attributes_test.py
- test/telemetry/configuration_test.py
- test/telemetry/counters_test.py
- test/telemetry/histograms_test.py
- test/telemetry/metrics_test.py
- test/telemetry/telemetry_test.py
This PR enhances the OpenTelemetry metrics reporting support released in 0.6.0:
- Adds `TelemetryConfiguration`, `TelemetryMetricsConfiguration` and `TelemetryMetricConfiguration` classes.
- Updates the `Configuration` class to accept a `TelemetryConfiguration` instance, for configuring what metrics and attributes will be used.
- Adds unit tests for all OpenTelemetry functionality.
> feat: enhancements to OpenTelemetry support

- openfga_sdk/sync/api_client.py
- openfga_sdk/telemetry/attributes.py
- openfga_sdk/telemetry/metrics.py
- test/telemetry/attributes_test.py
This PR fixes several bugs identified in the recent OpenTelemetry improvements:
- Fixed `http_client_request_duration` being reported in seconds rather than the intended milliseconds
- Fixed the sync client mistakenly passing the entire configuration (rather than just the OpenTelemetry configuration as intended) to `queryDuration()` and `requestDuration()`.
- Fixed an issue in which some attributes may not have been exported as expected under some conditions
- All attribute values are now correctly exported as their intended types rather than defaulting to strings
- Fixed an issue in which `queryDuration()` and `requestDuration()` may not have updated their histograms reliably when `attr_http_client_request_duration` or `attr_http_server_request_duration` (respectively) were not enabled …
> fix: OpenTelemetry bugfixes

- openfga_sdk/rest.py
- openfga_sdk/sync/rest.py
This change addresses inconsistencies between the sync and async clients when encountering HTTP status codes 429 or 400 in an HTTP response.
Closes #129
> fix: inconsistence in 429 handling between sync/async client

- openfga_sdk/client/client.py
- openfga_sdk/sync/client/client.py
This change addresses a bug where `batch_check` typing was configured to only accept `str`ing values as part of the `options` `dict`; however, the `max_parallel_requests` option (later used by the `ThreadPoolExecutor`) requires this to be an `int`eger value.
This PR:
- Updates the method signature to accept `str | int` as values for the `dict`.
- Adds a check to determine if `max_parallel_requests` was passed as an `str` or `int.`
- if it was passed as a `str`, and Python verifies the string represents a numerical value (using `isdigit()`), then the value is cast to an `int` and used.
- If it was passed as an `int,` the value is used.
closes #128
> fix: ensure `max_parallel_requests` is an `int` value in `batch_check`

- docs/opentelemetry.md
- example/opentelemetry/main.py
- openfga_sdk/__init__.py
- openfga_sdk/api/open_fga_api.py
- openfga_sdk/api_client.py
- openfga_sdk/configuration.py
- openfga_sdk/oauth2.py
- openfga_sdk/sync/api_client.py
- openfga_sdk/sync/oauth2.py
- openfga_sdk/sync/open_fga_api.py
- openfga_sdk/telemetry/__init__.py
- openfga_sdk/telemetry/attributes.py
- openfga_sdk/telemetry/configuration.py
- openfga_sdk/telemetry/counters.py
- openfga_sdk/telemetry/histograms.py
- openfga_sdk/telemetry/metrics.py
- openfga_sdk/telemetry/telemetry.py
- openfga_sdk/telemetry/utilities.py
- test/client/client_test.py
- test/sync/client/client_test.py
- test/telemetry/attributes_test.py
- test/telemetry/configuration_test.py
- test/telemetry/counters_test.py
- test/telemetry/histograms_test.py
- test/telemetry/metrics_test.py
- test/telemetry/telemetry_test.py
- test/telemetry/utilities_test.py
This change fixes some inconsistencies in how the Python SDK handles the configuration API for its OpenTelemetry support. These changes should improve the developer experience and general usage of the feature.
1. We can now permit a `dict`-style configuration to be provided, similar to how we support JSON-style approaches in some of the other SDKs.
Current behavior expects classes to be supplied:
```python
from openfga_sdk.telemetry.configuration import (
TelemetryConfiguration,
TelemetryMetricConfiguration,
TelemetryMetricsConfiguration,
)
from openfga_sdk import ClientConfiguration, OpenFgaClient
configuration = ClientConfiguration(
telemetry=TelemetryConfiguration(
metrics=TelemetryMetricsConfiguration(
histogram_request_duration=TelemetryMetricConfiguration( …
```
> refactor: improve OpenTelemetry configuration

- docs/opentelemetry.md
- openfga_sdk/api_client.py
- openfga_sdk/oauth2.py
- openfga_sdk/sync/api_client.py
- openfga_sdk/sync/oauth2.py
- openfga_sdk/telemetry/configuration.py
- openfga_sdk/telemetry/counters.py
- openfga_sdk/telemetry/histograms.py
- openfga_sdk/telemetry/metrics.py
- test/telemetry/counters_test.py
Added:
- Adds a per-HTTP request counter metric, `fga-client.request`. It is disabled by default.
Changed:
- Method signature on `credentialsRequest` now uses `1` as the default parameter value.
- Changed default unit type in `TelemetryCounter`/`TelemetryCounters`. It mistakenly used `milliseconds` as the default unit type for counters previously.
- Refactored `TelemetryHistogram`/`TelemetryHistograms` to use the shared default `milliseconds` unit type; not necessary to define it each time.
Fixed:
- Moved `fromRequest` step above exception handling in the synchronous API Client to ensure those attributes were properly collected there. This was already the case in the asynchronous API client.
- Moved `http.request.resend_count` increment to the top of the retry loop for the synchronous API …
> feat(OpenTelemetry): add per-HTTP request counter metric

- openfga_sdk/client/client.py
- openfga_sdk/sync/client/client.py
Currently the Python SDK is sending the sdk method header for all requests, the expectation (and behaviour in other SDKs) for this header is that it is only sent for SDK methods that are wrappers of APIs as the intent is to provide a way for implementors of OpenFGA to track usage of these SDK wrapper methods.
So it should be sent for:
- `read_latest_authorization_model`
- `write`
- Should also send `CLIENT_BULK_REQUEST_ID_HEADER` when not in transaction mode
- `write_tuples`
- Should also send `CLIENT_BULK_REQUEST_ID_HEADER` when not in transaction mode (handled via `write`)
- `delete_tuples`
- Should also send `CLIENT_BULK_REQUEST_ID_HEADER` when not in transaction mode (handled via `write`)
- `batch_check`
-   - Should also send `CLIENT_BULK_REQUEST_ID_HEADER`
- `list_relations`
- …
> fix: correct usage of the sdk method header

- example/example1/example1.py
- openfga_sdk/client/client.py
- openfga_sdk/sync/client/client.py
- test/client/client_test.py
- test/sync/client/client_test.py
This PR fixes some minor issues I noticed while updating the `openfga/api` sha on `main. Splitting out to a separate PR to help review.
They are as follows:
- the `ListUsers` API differs on the shape of `contextual_tuples`, rather than an object with a `tuple_keys` property it just takes the array directly. So we don't need the `ContextualTupleKeys` type
- `read_latest_authorization_model` errors if there are no models
- `list_users` in the example was using the wrong types
https://github.com/openfga/sdk-generator/pull/446
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
> Minor fixes

- openfga_sdk/configuration.py
- openfga_sdk/telemetry/attributes.py
- openfga_sdk/telemetry/configuration.py
- openfga_sdk/telemetry/counters.py
- openfga_sdk/telemetry/histograms.py
- openfga_sdk/telemetry/metrics.py
This PR removes the `Optional` type hinter, as guidance for Python 3.10+ and [PEP 604's introduction](https://peps.python.org/pep-0604/) is to phase it out in favor of a simple `None` union type. Note that these are functionally identical and do not affect the method signature for existing integrations.
- https://github.com/openfga/sdk-generator/pull/451
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
> chore: remove Optional typings

- README.md
- openfga_sdk/client/configuration.py
- openfga_sdk/configuration.py
- openfga_sdk/rest.py
- openfga_sdk/sync/rest.py
- test/api/open_fga_api_test.py
- test/configuration_test.py
- test/sync/open_fga_api_test.py
Syncs the new client wide request timeout and docs changes across from the generator ahead of a release
https://github.com/openfga/sdk-generator/pull/416
https://github.com/openfga/sdk-generator/pull/403
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
> Sync readme and client timeout changes

- CHANGELOG.md
We progressed forward in time since I wrote that entry
> docs: correct v0.9.0 release date

- openfga_sdk/rest.py
- openfga_sdk/sync/rest.py
- test/rest_test.py
- test/sync/rest_test.py
This is a minor bug fix to the new `stream` method added to the Python SDK's REST client in 0.9.1: the pool shouldn't close after the request concludes, as the same pool can continue to be used for future requests.
Generated from https://github.com/openfga/sdk-generator/pull/491
> fix: REST client should not close after `stream` request

- .github/workflows/main.yaml
- openfga_sdk/sync/rest.py
- requirements.txt
- Bumped dependency requirements for `urllib3` to specify >= v1.26.19 or >= v2.2.2
- Modified type hints in `RESTResponse` class to use `urllib3.HTTPResponse` instead of `urllib3.BaseHTTPResponse`
- Added matrix testing for different urllib3 versions in GitHub Actions workflow
> fix: urllib3 compatibility < v2

- openfga_sdk/oauth2.py
- test/oauth2_test.py
Use dynamic token issuer URL not applying a scheme and path if they are already provided.
Integrate changes from [SDK Generator](https://github.com/openfga/sdk-generator/pull/530).
> feat: dynamic token issuer

- CHANGELOG.md
- openfga_sdk/client/client.py
- openfga_sdk/sync/client/client.py
- test/client/client_test.py
- test/sync/client/client_test.py
- test/sync/open_fga_api_test.py
Thanks to @GMorris-professional for contributing these changes in https://github.com/openfga/sdk-generator/pull/516
```
ListRelations now throws the first error that occurs during one of the checks instead of swallowing it.
```
- https://github.com/openfga/sdk-generator/pull/516
- https://github.com/openfga/python-sdk/issues/173
- https://github.com/openfga/sdk-generator/issues/183
> fix: ListRelations should not swallow errors
